
FROM openjdk:21-slim

# create non-root user for security
RUN groupadd -r appuser && useradd -r -g appuser appuser

# set working dir
WORKDIR /app

COPY ./jar-context/build/sample-cobra-producer.jar app.jar

RUN chown -R appuser:appuser /app

USER appuser

# expose SpringBoot application port
EXPOSE 8080

ENV JAVA_OPTS="-Xmx512m -Xms256m -XX:MaxDirectMemorySize=512m -XX:+UseContainerSupport"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
